# Generated by Django 4.0.5 on 2022-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_projectscreenshot_projects_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revieww',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
