# Generated by Django 4.0.5 on 2022-06-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_revieww_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revieww',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainapp.projects'),
        ),
    ]
